### ISSUE TITLE
error:Error creating peer: EOF"

### ISSUE THREAD

**Issue by whodoyouremember** [Bytom/vapor#318]
下载地址https://github.com/Bytom/vapor/releases/download/v0.2.0/vapor-0.2.0-linux_amd64.tgz
系统ubuntu
命令：./vapord-linux_amd64 node
然后出现这种错误
 moniker: , network: solonet [listen 192.168.31.9:46658],networkID: 1018cf0611c6ee09, service: 7,version: 1.0.9+0af46f9b ([])}"
time="Jul 18 17:47:09.162" level=info msg="Rpc listen" api address:="0.0.0.0:9889" module=api
time="Jul 18 17:47:09.167" level=info msg="Launching System Browser with :http://127.0.0.1:9889"
time="Jul 18 17:47:09.168" level=error msg="webbrowser: tried to open \"http://127.0.0.1:9889\", but you are running a shell session"
time="Jul 18 17:47:09.169" level=info msg="start node complete" duration=154.966055ms module=cmd
time="Jul 18 17:47:09.168" level=info msg="Ignoring inbound connection: error while adding peer. address:192.168.xx.xx:36960 error:Error creating peer: EOF"
那个地方操作错了吗？

IP地址做了处理

**Comment by zcc0721** [comment]
启动之前使用 vapord init 命令初始化了吗

**Comment by whodoyouremember** [comment]
使用了vapord init --chain_id=vapor这个命令

**Comment by zcc0721** [comment]
初始化错误了，网络 id 分别为 mainnet、testnet 和 solonet

**Comment by zcc0721** [comment]
网络 id 更改过

**Comment by whodoyouremember** [comment]
如果我要用ubuntu启动vapor要怎样输入什么样的命令？第一步先初始化命令是vapord init --chain_id=mainnet。第二步命令为vapord node。是这样吗？我刚刚试了一下又碰到刚才的错误。

**Comment by whodoyouremember** [comment]
如果我要用ubuntu启动vapor要怎样输入什么样的命令？第一步先初始化命令是vapord init --chain_id=mainnet。第二步命令为vapord node。是这样吗？我刚刚试了一下又碰到刚才的错误。

**Comment by whodoyouremember** [comment]
root@c:~/vapor# ./vapord-linux_amd64 init --chain_id=solonet
time="Jul 19 14:20:37.834" level=panic msg="Already exists config file." config=/root/.vapor/config.toml module=cmd
panic: (*logrus.Entry) (0xc3a340,0xc420080ff0)

goroutine 1 [running]:
github.com/vapor/vendor/github.com/sirupsen/logrus.Entry.log(0xc420080140, 0xc420163c50, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc400000000, ...)
	/home/yahtoo/go/src/github.com/vapor/vendor/github.com/sirupsen/logrus/entry.go:128 +0x59c
github.com/vapor/vendor/github.com/sirupsen/logrus.(*Entry).Panic(0xc420080fa0, 0xc42011f4b8, 0x1, 0x1)
	/home/yahtoo/go/src/github.com/vapor/vendor/github.com/sirupsen/logrus/entry.go:173 +0xaa
github.com/vapor/cmd/vapord/commands.initFiles(0x1791ac0, 0xc4201a3f60, 0x0, 0x1)
	/home/yahtoo/go/src/github.com/vapor/cmd/vapord/commands/init.go:31 +0xfbc
github.com/vapor/vendor/github.com/spf13/cobra.(*Command).execute(0x1791ac0, 0xc4201a3f30, 0x1, 0x1, 0x1791ac0, 0xc4201a3f30)
	/home/yahtoo/go/src/github.com/vapor/vendor/github.com/spf13/cobra/command.go:702 +0x2c6
github.com/vapor/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1791ce0, 0xb8e760, 0xc42011fe01, 0xc4201ae440)
	/home/yahtoo/go/src/github.com/vapor/vendor/github.com/spf13/cobra/command.go:783 +0x2e4
github.com/vapor/vendor/github.com/spf13/cobra.(*Command).Execute(0x1791ce0, 0xc4201ae440, 0xc42011ff30)
	/home/yahtoo/go/src/github.com/vapor/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/vapor/vendor/github.com/tendermint/tmlibs/cli.Executor.Execute(0x1791ce0, 0x1361fc8, 0x2, 0xc4201a8e00)
	/home/yahtoo/go/src/github.com/vapor/vendor/github.com/tendermint/tmlibs/cli/setup.go:83 +0x4e
main.main()
	/home/yahtoo/go/src/github.com/vapor/cmd/vapord/main.go:56 +0x78
root@c:~/vapor# ./vapord-linux_amd64 node
time="Jul 19 14:20:46.126" level=info fed_controlprogram=ae2050ef22b3a3fca7bc08916187cc9ec2f4005c9c6b1353aa1decbd4be3f3bb0fbe5151ad fed_quorum=1 fed_xpubs="[50ef22b3a3fca7bc08916187cc9ec2f4005c9c6b1353aa1decbd4be3f3bb0fbe1967589f0d9dec13a388c0412002d2c267bdf3b920864e1ddc50581be5604ce1]" module=node pubkey=8bd51165b82ce4fbd21976b5ada43fe65f8a096c9b79516c64f3cc21cdb1d58bab214e9ef530c682342bae71eac1a9ab3ac1c4f58dcc43c0e26bd70671e24c66
time="Jul 19 14:20:46.770" level=info msg="Local listener ip::: port:46658"
time="Jul 19 14:20:46.893" level=info msg="get UPNP external address" err="could not add tcp UPNP port mapping: Error 500 for AddPortMapping" module=p2p
time="Jul 19 14:20:46.894" level=info msg="get ipv4 external address success" addr="192.168.xx.xx:46658" module=p2p
time="Jul 19 14:20:46.963" level=info msg="UDP listener up v5" module=discover net="enode://8bd51165b82ce4fbd21976b5ada43fe65f8a096c9b79516c64f3cc21cdb1d58b@[::]:46658"
time="Jul 19 14:20:46.965" level=error msg="fail on query dns seeds" err="dns seeds is empty" module=discover
time="Jul 19 14:20:47.065" level=info msg="init p2p network" module=p2p nodeInfo="NodeInfo{pk: 8bd51165b82ce4fbd21976b5ada43fe65f8a096c9b79516c64f3cc21cdb1d58bab214e9ef530c682342bae71eac1a9ab3ac1c4f58dcc43c0e26bd70671e24c66, moniker: , network: solonet [listen 192.168.31.9:46658],networkID: 1018cf0611c6ee09, service: 7,version: 1.0.9+0af46f9b ([])}"
time="Jul 19 14:20:47.066" level=info msg="Rpc listen" api address:="0.0.0.0:9889" module=api
time="Jul 19 14:20:47.094" level=info msg="Launching System Browser with :http://127.0.0.1:9889"
time="Jul 19 14:20:47.102" level=error msg="webbrowser: tried to open \"http://127.0.0.1:9889\", but you are running a shell session"
time="Jul 19 14:20:47.102" level=info msg="start node complete" duration=1.96085612s module=cmd
time="Jul 19 14:20:47.085" level=info msg="Ignoring inbound connection: error while adding peer. address:192.168.xxxxx.xx:45160 error:Error creating peer: EOF"

**Comment by zcc0721** [comment]
现在主网还没有发布，所有网络 id 只能填写 testnet 或者 solonet，明天主网发布

**Comment by zcc0721** [comment]
你的代码有没有拉取 master 最新版？首先获取 master 分支最新版代码，然后初始化的时候指定一个新的数据目录或者删除原来的数据目录，然后才启动

**Comment by zcc0721** [comment]
删除 /root/.vapor/ 下的所有文件

**Comment by whodoyouremember** [comment]
我没有去编译代码，我是直接下载的这个linux文件，尝试直接启动一个节点。下载地址：https://github.com/Bytom/vapor/releases/download/v0.2.0/vapor-0.2.0-linux_amd64.tgz

**Comment by zcc0721** [comment]
上面的代码很老了，种子节点 ip，区块信息等都改了。你要么等明天的主网发布之后最新代码，要么手动 clone master 分支最新代码，之后自己运行 make install 自己编译

**Comment by whodoyouremember** [comment]
好的，感谢

**Comment by zcc0721** [comment]
自己编译也很简单，配置好 go 环境，直接运行 make install 之后就可以使用 vapord init 和 vapord node了
