### ISSUE TITLE
Ignoring inbound connection: error while adding peer

### ISSUE THREAD

**Issue by whodoyouremember** [Bytom/vapor#348]
运行环境
ubuntu和https://github.com/Bytom/vapor/releases/download/v1.0.0/vapor-1.0.0-linux_amd64.tgz

报错信息
root@c:~# ./vapord init --chain_id=vapor
time="Jul 24 14:35:58.829" level=info msg="success generate private" pubkey=94bd130e6749feb29bdc9e1383e573cceee1fa9a9a8016836260933947a2ed2544bc267ecd63ed5f862179414b2d4f240c35fc7e73f912cd1a329d312f7e0d3c
time="Jul 24 14:35:58.829" level=info msg="Initialized bytom" config=/root/.vapor/config.toml module=cmd
root@c:~# ./vapord node
time="Jul 24 14:36:06.296" level=info fed_controlprogram=0020f86826d640810eb08a2bfb706e0092273e05e9a7d3d71f9d53f4f6cc2e3d6c6a fed_quorum=2 fed_xpubs="[580daf48fa8962100047cb1391da890bb7f2c849fdbc9b368cb4394a4c7cbb0977e2e7ebbf055dc0ef90af6a0d2af01ce7ec56b735d016aab597815ec48552e5 f3f6bcf61b65fa9d1566455a5688ca8b395efdc22e654963134b5e5cb0a45d8be522d21abc384a73177a7b9d64eba915fcfe2862d86a508a3c46dc410bdd72ad 53559612f2b7bcada18948b7de39d63947a0e2bd7336d07db1350c54ba5743996b84bf9d18ff7a2457e1a5c70ce5013e4a3b62666ddb03294c53051d5f5c70c0 7c88cc58adfc71818b08308d43c29de22460b0ea6895449cbec6e458d7dc09e0aea243fa5075ee6621da0d805bd047f6bb207329c5bd2ca3253b172fb323b512]" module=node pubkey=94bd130e6749feb29bdc9e1383e573cceee1fa9a9a8016836260933947a2ed2544bc267ecd63ed5f862179414b2d4f240c35fc7e73f912cd1a329d312f7e0d3c
time="Jul 24 14:36:06.335" level=info msg="block saved on disk" duration="103.902µs" hash=13dfbea05eca78c809ee760de2cc66f6f204be0967974061b13c4d24026e4424 height=0 module=leveldb
time="Jul 24 14:36:06.707" level=info msg="Local listener ip::: port:56658"
time="Jul 24 14:36:06.822" level=info msg="get UPNP external address" err="<nil>" module=p2p
time="Jul 24 14:36:06.831" level=info msg="UDP listener up v5" module=discover net="enode://94bd130e6749feb29bdc9e1383e573cceee1fa9a9a8016836260933947a2ed25@[::]:56658"
time="Jul 24 14:36:06.832" level=error msg="fail on query dns seeds" err="dns seeds is empty" module=discover
time="Jul 24 14:36:06.838" level=info msg="init p2p network" module=p2p nodeInfo="NodeInfo{pk: 94bd130e6749feb29bdc9e1383e573cceee1fa9a9a8016836260933947a2ed2544bc267ecd63ed5f862179414b2d4f240c35fc7e73f912cd1a329d312f7e0d3c, moniker: , network: solonet [listen 222.65.108.44:56658],networkID: 74f54616a3108275, service: 7,version: 1.0.0+3a6cd964 ([])}"
time="Jul 24 14:36:06.839" level=info msg="Rpc listen" api address:="0.0.0.0:9889" module=api
time="Jul 24 14:36:06.843" level=info msg="Launching System Browser with :http://127.0.0.1:9889"
time="Jul 24 14:36:06.844" level=error msg="webbrowser: tried to open \"http://127.0.0.1:9889\", but you are running a shell session"
time="Jul 24 14:36:06.845" level=info msg="start node complete" duration=550.000643ms module=cmd
time="Jul 24 14:36:09.247" level=info msg="Peer handshake" address="192.168.31.140:42432" module=p2p
time="Jul 24 14:36:09.249" level=info msg="Ignoring inbound connection: error while adding peer. address:192.168.31.140:42432 error:Connect self"
time="Jul 24 14:36:09.249" level=info msg="Peer handshake" address="192.168.31.140:56658" module=p2p
time="Jul 24 14:36:09.252" level=error msg="DialPeer fail on switch AddPeer"  err="Connect self" address="192.168.31.140:56658" module=p2p
time="Jul 24 14:36:09.253" level=error msg="dialPeerWorker fail on dial peer" addr="192.168.31.140:56658" err="Connect self" module=p2p
time="Jul 24 14:40:44.056" level=error msg="DialPeer fail on newOutboundPeerConn"  err="Error creating peer: unexpected EOF" address="192.168.31.216:46657" module=p2p
time="Jul 24 14:40:44.056" level=error msg="dialPeerWorker fail on dial peer" addr="192.168.31.216:46657" err="Error creating peer: unexpected EOF" module=p2p
time="Jul 24 14:40:47.052" level=error msg="DialPeer fail on newOutboundPeerConn"  err="Error dial peer: dial tcp 192.168.226.1:46657: i/o timeout" address="192.168.226.1:46657" module=p2p
time="Jul 24 14:40:47.053" level=error msg="dialPeerWorker fail on dial peer" addr="192.168.226.1:46657" err="Error dial peer: dial tcp 192.168.226.1:46657: i/o timeout" module=p2p
time="Jul 24 14:40:47.054" level=error msg="DialPeer fail on newOutboundPeerConn"  err="Error dial peer: dial tcp 192.168.111.1:46657: i/o timeout" address="192.168.111.1:46657" module=p2p
time="Jul 24 14:40:47.054" level=error msg="dialPeerWorker fail on dial peer" addr="192.168.111.1:46657" err="Error dial peer: dial tcp 192.168.111.1:46657: i/o timeout" module=p2p
time="Jul 24 14:42:28.346" level=info msg="Ignoring inbound connection: error while adding peer. address:162.243.163.107:32766 error:Error creating peer: read tcp 192.168.xxxxx。xxx:56658->162.243.163.107:32766: i/o timeout"

好像有个节点挂了，我链接不上去
root@c:~# ping 162.243.163.107
PING 162.243.163.107 (162.243.163.107) 56(84) bytes of data.
64 bytes from 162.243.163.107: icmp_seq=1 ttl=45 time=219 ms
64 bytes from 162.243.163.107: icmp_seq=3 ttl=45 time=216 ms
64 bytes from 162.243.163.107: icmp_seq=4 ttl=45 time=216 ms

**Comment by HAOYUatHZ** [comment]
how is it going

**Comment by whodoyouremember** [comment]
ok
