### ISSUE TITLE
VM虚拟机运行Ubuntu虚拟机中的vopar会导致Windows磁盘增到导致节点挂掉

### ISSUE THREAD

**Issue by whodoyouremember** [Bytom/vapor#351]
环境
vm 12
ubuntu
https://github.com/Bytom/vapor/releases/download/v1.0.0/vapor-1.0.0-linux_amd64.tgz

正常运行vapor节点
然后发现windows磁盘无节制增大，导致磁盘满了造成VM虚拟机挂掉，从而导致节点挂掉
但是虚拟机中的ubuntu系统磁盘大小无变化。。。。。

懵逼树上懵逼果，懵逼树下只有我

**Comment by whodoyouremember** [comment]
我重新删除空间，目前消耗了70-80个G就不在增加了

**Comment by whodoyouremember** [comment]
不是不增加了，只是增加的慢了

**Comment by HAOYUatHZ** [comment]
plz upgrade to the most update version
